junit:
 stage: test
 script:
  - mvn -B -f mavenproj clean test
generate_artifacts:
 stage: deploy
 script:
  - mvn -B -f mavenproj clean site package
 artifacts:
  paths:
   - mavenproj/target/mavenproj*.jar
