junit:
 stage: test
 script: 
  - mvn -B -f MainBuild clean test -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k
generate_artifacts:
 stage: deploy
 script:
  - mvn -B -f MainBuild clean site package
 artifacts:
  paths:
   - MainBuild/target/MainBuild*.jar
   - MainBuild/src/main/java/seng202/team10/Main.java
