junit:
 stage: test
 script:
  - mvn -B -f MainBuild clean test -Dprism.verbose=true
generate_artifacts:
 stage: deploy
 script:
  - mvn -B -f MainBuild clean site package
 artifacts:
  paths:
   - MainBuild/target/MainBuild*.jar
   - MainBuild/src/main/java/seng202/team10/Main.java
