junit:
 stage: test
 script:
  - mvn -B -f "Main Build" clean test
generate_artifacts:
 stage: deploy
 script:
  - mvn -B -f "Main Build" clean site package
 artifacts:
  paths:
   - "Main Build/target/Main Build*.jar"
   - "Main Build/src/main/java/seng202/team10/App.java"
